### ISSUE TITLE
Sync with ExoPlayer-1.5

### ISSUE THREAD

**Issue by perchrh** [fougere-mike/ExoPlayer#3]
Do you plan to merge in the latest fixes and improvements from ExoPlayer?
1.5.4 changed some interfaces, but 1.5.3 is perhaps an easy merge.

**Comment by fougere-mike** [comment]
It's on my to-do list, but I'm probably going to hold off for another few weeks. 

There are a few PRs open that will (hopefully) implement live seeking for HLS. I haven't had a chance to evaluate them yet, but after reading the diffs quickly, it looks similar to what I've done. 

I'd like to see those get merged before I spend the time moving to the new interfaces. If they work as advertised, this fork will become redundant. 

However the pace has been quite slow. If they're not merged in the next month or so I'll likely sync the repos anyways.

**Comment by jglanfield** [comment]
Hi there, any updates on this? I'd love to test it out.

**Comment by fougere-mike** [comment]
Hm, never got around to this, but ExoPlayer _did_ add HLS seeking eventually. Closing.
